services:
  db:
    container_name: postgres-course
    image: postgres
    environment:
      POSTGRES_USER: course-system
      POSTGRES_PASSWORD: password
      POSTGRES_DB: course_system
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
volumes:
  db: